config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :admin do
    resources :articles do
      get 'new_category', on: :collection
      get 'new_tag', on: :collection
      post 'create_category', on: :collection
      post 'create_tag', on: :collection
    end
    resources :assets
    resources :reports do
      get 'download'
      post 'download_file'
    end
  end

  resources :admin do
    get 'dashboard', on: :collection
    get 'reports', on: :collection
    get 'upload', on: :collection
    post 'save_asset', on: :collection
  end

  get '/our-services' => 'home#services', :as => 'services'
  get '/show-case' => 'home#show_case', :as => 'show_case'
  get '/history' => 'home#history', :as => 'history'
  get '/contact-us' => 'home#contact_us', :as => 'contact_us'
  get '/downloads' => 'home#downloads', :as => 'downloads'
  get '/events' => 'home#events_list', :as => 'events_list'
  get '/events/aayudh' => 'home#event_show', :as => 'event_show'

  get '/quote' => 'home#quote', :as => 'quote_form'
  post 'submit_quote' => 'home#submit_quote', :as => 'submit_quote'

  get '/download/:alias_name(/:access_code)' => "home#get_file"

  get '/login' => 'home#login', :as => 'login' #needs to be changed

  post '/home/add_to_newsletter', :as => 'add_to_newsletter'

  get 'blog/articles' => 'blog#list_blog', as: "list_blog_articles"
  get 'blog/articles/:article_alias_name' => 'blog#show_blog', as: "blog_article"
  get 'blog/categories/:category_alias_name' => 'blog#category_articles', as: "category_articles"
  get 'blog/tag/:tag_alias_name' => 'blog#tag_articles', as: "tag_articles"

end

app/models/article.rb
class Article < ActiveRecord::Base

  has_one :article_content
  has_and_belongs_to_many :tags
  belongs_to :category

  validates :title, presence: true
  validates :alias_url, uniqueness: true, allow_blank: true

  delegate :content, :page_title, :banner_image_url, :meta_keywords, :meta_description, to: :article_content

  scope :by_sequence, -> { order('sequence_number asc') }
  scope :by_updated, -> { order('updated_at desc') }
  scope :order_by_type, -> { order('article_type') }
  scope :published, -> { where('status =?', true) }
  scope :by_type, -> (type) { where('article_type =?', type) }
  scope :published_blog, -> { where('article_type = ? and status = ?', 'Blog', true) }
  scope :published_services, -> { where('article_type = ? and status = ? and heading_block = ?', 'Article', true, 'Services') }
  scope :published_events, -> { where('article_type = ? and status = ? and heading_block = ?', 'Article', true, 'Events') }
  scope :by_category, -> (id) { where('category_id = ?', id) }
  scope :by_tag, -> (id) { where('articles_tags.tag_id = (?)', id) }

  def display_date
    self["display_date"].strftime("%F %T") rescue nil
  end

  def status
    self["status"] ? true : false
  end

  def image_url
    self.article_content.banner_image_url
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController

  def new_category
    @page_properties = {:header => "Create New Category"}
    @category=Category.new
  end

  def create_category
    category=Category.new(category_params)
    category.save ? (redirect_to admin_articles_path) : (render 'new_category')
  end

  def new_tag
    @page_properties = {:header => "Create New Tag"}
    @tag=Tag.new
  end

  def create_tag
    tag=Tag.new(tag_params)
    tag.save ? (redirect_to admin_articles_path) : (render 'new_tag')
  end

  def new
    @article = Article.new
    @page_properties = {:header => "Create New Article"}
  end

  def create
    article = Article.new(article_params)
    Article.transaction do
      render 'new' and return unless article.save!
      render 'new' and return unless article.create_article_content!(article_content_params)
      redirect_to admin_articles_url
    end
  end

  def edit
    @page_properties = {:header => "Edit Article"}
    @article = Article.find(params[:id])
    @article_content = @article.article_content
  end

  def update
    @article = Article.find(params[:article][:id])
    @article_content = @article.article_content
    if @article.update_attributes(article_params) and @article_content.update_attributes(article_content_params)
      redirect_to admin_articles_url
    else
      render 'edit'
    end
  end

  def index
    @page_properties = {:header => "Article Listing"}
    @articles = Article.order_by_type
  end

  private

  def article_params
    params.require(:article).permit(:id, :title, :description, :status, :alias_url, :article_type, :status, :sequence_number, :heading_block, :author, :category_id, :display_date, :tag_ids=>[])
  end

  def article_content_params
    params[:article].require(:article_content).permit(:banner_image_url, :page_title, :meta_keywords, :meta_description, :content)
  end

  def category_params
    params.require(:category).permit(:name, :full_name, :alias_name, :sequence_number, :status)
  end

  def tag_params
    params.require(:tag).permit(:name, :alias_name, :status)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def page_properties_for(page)
    mapping = {
        :list_blog => {
            :page_title => "Our Blog"
        },
        :show_blog => {
            :half_banner=>true,
        },
        :tag_articles => {
            :half_banner => true
        },
        :category_articles => {
            :half_banner => true
        }
    }

    mapping[page.to_sym]
  end

end

app/views/admin/articles/_form.html.erb
<div class="container-block col-md-12 col-sm-12 col-xs-12 no-padding">

  <div class="form-block col-md-12 col-sm-12 col-xs-12 no-padding">
    <div class="container no-padding">
      <div class="row">

        <h2><a class="border"><%= @page_properties[:header] %></a></h2>

        <%# value = params[:action] == "new_articles" ? :New : :Edit %>
        <%# @breadcrumb = {:Home => root_url, :List_Articles => list_articles_path, value => "#"} %>
        <%#= render :partial => 'layouts/breadcrumb' %>

        <%= form_for ([:admin, @article]), :controller => "admin/articles", :action => @article.new_record? ? :create : :update, :method => @article.new_record? ? "post" : "put", html: { autocomplete: "off", :id => 'article_form' } do |f| %>

            <%#= semantic_form_for ([:admin, @article]),:controller => "admin/articles", :action => @article.new_record? ? :create : :update, :html => {:name => "article", :method => @article.new_record? ? "post" : "put"} do |f| %>

            <%= f.hidden_field 'id', :value => @article.id %>

            <p class="col-md-5 col-sm-12 col-xs-12 text-field">
              <%= f.text_field :title, :class => 'form-white' ,:placeholder => 'Title'%>
            </p>

            <p class="col-md-5 col-sm-8 col-xs-12 text-field">
              <%= f.text_field :alias_url, :class => 'form-white', :placeholder => 'Alias URL' %>
            </p>

            <p class="col-md-2 col-sm-4 col-xs-12 text-field">
              <%= f.text_field :sequence_number, :class => 'form-white', :placeholder => 'Sequence Number' %>
            </p>

            <p class="col-md-12 col-sm-12 col-xs-12 text-field">
              <%= f.text_area :description, :class => 'form-white', :placeholder => 'Description', :rows => 1 %>
            </p>



            <div class="col-md-4 col-sm-6 col-xs-12 check-box">
              <label>Published</label>
              <%= custom_check_box_3("article[status]", true, @article.status, "article_status", "Yes", "No") %>
            </div>

            <p class="col-md-4 col-sm-6 col-xs-12 select-box article-type" data-content="Article Type">
              <%= select_tag "article[article_type]", options_for_select(ARTICLE_TYPES, @article.article_type), :class => "cs-select cs-skin-elastic", prompt: "--Article Type--" %>
            </p>

            <div class="col-md-4 col-sm-6 col-xs-12 all-article-type Article-article-type no-padding">
              <p class="col-md-12 col-sm-12 col-xs-12 select-box" data-content="Heading Block">
                <%= select_tag "article[heading_block]", options_for_select(BLOCK_SELECTOR, @article.heading_block), :class => "cs-select cs-skin-elastic", prompt: "--Heading Block--" %>
              </p>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12 all-article-type Blog-article-type no-padding">
              <p class="col-md-12 col-sm-12 col-xs-12 select-box" data-content="Author">
                <%= select_tag "article[author]", options_for_select(AUTHORS, @article.author), :class => "cs-select cs-skin-elastic", prompt: "--Select Author--" %>
              </p>
            </div>

            <div class="col-md-12 col-sm-12 col-xs-12 all-article-type Blog-article-type no-padding">
              <p class="col-md-4 col-sm-6 col-xs-12 select-box" data-content="Category">
                <%= collection_select(:article, :category_id, Category.all, :id, :name, options={:selected => @article.category.try(:id), :include_blank => '--Select Category--'}, {class: "cs-select cs-skin-elastic"} ) %>
              </p>

              <p class="col-md-4 col-sm-6 col-xs-12 auto-complete" data-content="Tags">
                <%= raw custom_autocomplete("article[tag_ids]", Tag.all, "name", @article.tags) %>
              </p>

              <div class="col-md-4 col-sm-6 col-xs-12 date-picker from-date" data-content="Display Date">
                <%= f.text_field :display_date, {:class => 'form-white' ,:placeholder => 'Display Date', id: 'display-date'} %>
                <div id="display-date-field"></div>
              </div>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12 all-article-type Static-Page-article-type  no-padding">
              <p class="col-md-12 col-sm-12 col-xs-12 select-box">
                <%#= select_tag "article[article_type]", options_for_select(["Articles", "Blog", "Static-Page"], @article.article_type), :class => "cs-select cs-skin-elastic", prompt: "--Article Type--" %>
              </p>
            </div>

            <%= f.fields_for :article_content do |e| %>

                <div class="col-md-12 col-sm-12 col-xs-12 no-padding">
                  <p class="col-md-6 col-sm-6 col-xs-12 text-field">
                    <%= e.text_field :banner_image_url, :class => 'form-white', :placeholder => 'Banner Image URL', :value => @article_content.try(:banner_image_url) %>
                  </p>

                  <p class="col-md-6 col-sm-6 col-xs-12 text-field">
                    <%= e.text_field :page_title, :class => 'form-white', :placeholder => 'Page Title', :value => @article_content.try(:page_title) %>
                  </p>

                  <p class="col-md-12 col-sm-12 col-xs-12 text-field">
                    <%= e.text_field :meta_keywords, :class => 'form-white', :placeholder => 'Meta Keywords', :value => @article_content.try(:meta_keywords) %>
                  </p>

                  <p class="col-md-12 col-sm-12 col-xs-12 text-field">
                    <%= e.text_area :meta_description, :class => 'form-white', :placeholder => 'Meta Description', :value => @article_content.try(:meta_description), :rows => 1 %>
                  </p>
                </div>

                <p class="col-md-12 col-sm-12 col-xs-12 tinymce-content">
                  <%#= f.text_area :content, :class => 'form-white', :placeholder => 'Content', :rows => 5 %>
                  <%= e.text_area :content, :class => "tinymce", :placeholder => 'Content', :value => @article.article_content.try(:content) %>
                </p>

            <% end %>

            <div class="col-md-12 col-sm-12 col-xs-12 submit-button">
              <%#= f.submit "Create Article", :class => "submit_btn" %>
              <%= custom_button_3(value:(@article.new_record? ? "Add" : "Update") + " Article") %>
            </div>

        <% end %>

      </div><!--ROW-->
    </div><!--CONTAINER-->
  </div><!--SERVICE-BLOCK-->
</div><!--CONTAINER-BLOCK-->


<%= tinymce :plugins => ["wordcount", "paste", "preview", "code", "table", "searchreplace", "image"], :toolbar => ["formatselect | searchreplace undo redo | bullist numlist | code image"] %>

<script>
  $('#display-date-field').calendar({
    trigger: '#display-date',
    zIndex: 999,
    onSelected: function (view, date, data) {
      console.log('event: onSelected')
    },
    onClose: function (view, date, data) {
      console.log('event: onClose');
      console.log('view:' + view);
      console.log('date:' + date);
      console.log('data:' + (data || 'None'));
    }
  });
</script>

app/views/admin/articles/index.html.erb
<div class="container-block col-md-12 col-sm-12 col-xs-12 no-padding">
  <div class="info-block col-md-12 col-sm-12 col-xs-12 no-padding" id="our-modules">
    <div class="container no-padding">
      <div class="row">

        <div class="info-common-block col-md-12 col-sm-12 col-xs-12 no-padding">
          <h2 id="contact"><a class="border"><%= @page_properties[:header] %></a></h2>

          <%# @breadcrumb = {:Home => root_url, :List_Articles => "#"} %>
          <%#= render :partial => 'layouts/breadcrumb' %>

          <div class="new-button">
            <%= custom_link_1("New Article", new_admin_article_path) %>
            <%= custom_link_1("New Category", new_category_admin_articles_path) %>
            <%= custom_link_1("New Tag", new_tag_admin_articles_path) %>
          </div>

          <% @articles.each do |article| %>

              <div class="article-list-block col-md-4 col-sm-6 col-xs-12">
                <a href="/admin/articles/<%= article.id %>/edit">
                  <div class="article-content article-content-<%= article.status %>">
                    <h4><%= article.title %></h4>
                    <p><%= article.article_type %></p>
                  </div>
                </a>
              </div>

          <% end %>

        </div><!--INFO-COMMON-BLOCK-->
      </div><!--ROW-->
    </div><!--CONTAINER-->
  </div><!--INFO-BLOCK-->
</div><!--CONTAINER-BLOCK-->

app/views/admin/articles/new_category.html.erb
<div class="container-block col-md-12 col-sm-12 col-xs-12 no-padding">

  <div class="form-block col-md-12 col-sm-12 col-xs-12 no-padding">
    <div class="container no-padding">
      <div class="row">

        <h2><a class="border"><%= @page_properties[:header] %></a></h2>

        <%= form_for ([:admin, @category]), url: create_category_admin_articles_path, html: { autocomplete: "off", :id => 'category_form' } do |f| %>

            <p class="col-md-6 col-sm-12 col-xs-12 text-field">
              <%= f.text_field :name, :class => 'form-white' ,:placeholder => 'Name'%>
            </p>

            <p class="col-md-6 col-sm-6 col-xs-12 text-field">
              <%= f.text_field :full_name, :class => 'form-white', :placeholder => 'Full Name' %>
            </p>

            <p class="col-md-5 col-sm-6 col-xs-12 text-field">
              <%= f.text_field :alias_name, :class => 'form-white', :placeholder => 'Alias Name' %>
            </p>

            <p class="col-md-3 col-sm-6 col-xs-12 text-field">
              <%= f.text_field :sequence_number, :class => 'form-white', :placeholder => 'Sequence Number' %>
            </p>

            <div class="col-md-4 col-sm-6 col-xs-12 check-box">
              <label>Published</label>
              <%= custom_check_box_3("category[status]", true, @category.status, "article_status", "Yes", "No") %>
            </div>

            <div class="col-md-12 col-sm-12 col-xs-12 submit-button">
              <%= custom_button_3(value:"Add Category") %>
            </div>
        <% end %>

      </div><!--ROW-->
    </div><!--CONTAINER-->
  </div><!--SERVICE-BLOCK-->
</div><!--CONTAINER-BLOCK-->

app/views/admin/articles/new_tag.html.erb
<div class="container-block col-md-12 col-sm-12 col-xs-12 no-padding">

  <div class="form-block col-md-12 col-sm-12 col-xs-12 no-padding">
    <div class="container no-padding">
      <div class="row">

        <h2><a class="border"><%= @page_properties[:header] %></a></h2>

        <%= form_for ([:admin, @tag]), url: create_tag_admin_articles_path, html: { autocomplete: "off", :id => 'tag_form' } do |f| %>

            <p class="col-md-4 col-sm-12 col-xs-12 text-field">
              <%= f.text_field :name, :class => 'form-white' ,:placeholder => 'Name'%>
            </p>

            <p class="col-md-4 col-sm-12 col-xs-12 text-field">
              <%= f.text_field :alias_name, :class => 'form-white', :placeholder => 'Alias Name' %>
            </p>

            <div class="col-md-4 col-sm-6 col-xs-12 check-box">
              <label>Published</label>
              <%= custom_check_box_3("tag[status]", true, @tag.status, "tag_status", "Yes", "No") %>
            </div>

            <div class="col-md-12 col-sm-12 col-xs-12 submit-button">
              <%= custom_button_3(value:"Add Tag") %>
            </div>

        <% end %>

      </div><!--ROW-->
    </div><!--CONTAINER-->
  </div><!--SERVICE-BLOCK-->
</div><!--CONTAINER-BLOCK-->
