config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :admin do
    resources :articles do
      get 'new_category', on: :collection
      get 'new_tag', on: :collection
      post 'create_category', on: :collection
      post 'create_tag', on: :collection
    end
    resources :assets
    resources :reports do
      get 'download'
      post 'download_file'
    end
  end

  resources :admin do
    get 'dashboard', on: :collection
    get 'reports', on: :collection
    get 'upload', on: :collection
    post 'save_asset', on: :collection
  end

  get '/our-services' => 'home#services', :as => 'services'
  get '/show-case' => 'home#show_case', :as => 'show_case'
  get '/history' => 'home#history', :as => 'history'
  get '/contact-us' => 'home#contact_us', :as => 'contact_us'
  get '/downloads' => 'home#downloads', :as => 'downloads'
  get '/events' => 'home#events_list', :as => 'events_list'
  get '/events/aayudh' => 'home#event_show', :as => 'event_show'

  get '/quote' => 'home#quote', :as => 'quote_form'
  post 'submit_quote' => 'home#submit_quote', :as => 'submit_quote'

  get '/download/:alias_name(/:access_code)' => "home#get_file"

  get '/login' => 'home#login', :as => 'login' #needs to be changed

  post '/home/add_to_newsletter', :as => 'add_to_newsletter'

  get 'blog/articles' => 'blog#list_blog', as: "list_blog_articles"
  get 'blog/articles/:article_alias_name' => 'blog#show_blog', as: "blog_article"
  get 'blog/categories/:category_alias_name' => 'blog#category_articles', as: "category_articles"
  get 'blog/tag/:tag_alias_name' => 'blog#tag_articles', as: "tag_articles"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  include ArticlesHelper

  def get_file
    asset=Asset.find_by_alias_name(params[:alias_name])
    if asset.present?
      if asset.access_code <= params[:access_code].to_i
        send_file "#{Rails.root}/private#{asset.location}"
      else
        redirect_to get_access_code_url, :alias_name=>params[:alias_name]
      end
    else
      redirect_to root_url
    end
  end

  def index
    @services=Article.published_services.by_sequence
    @gallery=Gallery.by_active
    @newsletter=Newsletter.first
  end

  def services
    @articles=Article.published_services.by_sequence
  end

  def show_case
    @gallery=Gallery.all
  end

  def add_to_newsletter
    sleep(3)
    render json: {status: false, message: "Email-id can't be empty"} and return if params[:email].blank?
    subscriber=Subscriber.find_by_email(params[:email]) || Subscriber.create(email: params[:email], status: "Newslettered")
    newsletter=Newsletter.find(params[:newsletter_id])

    render json: {status: true, message: "Already in the list"} and return if subscriber.newsletter_ids.include?(newsletter.id)

    subscriber.newsletter_ids=newsletter.id
    render json: {status: true, message: "Added to the Queue"}
  end

  def submit_quote

  end

  def downloads
    @assets=Asset.all_documents.active.by_sequence
  end

  def events_list
    @events=Article.published_events
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact_us.html.erb
<%= stylesheet_link_tag 'site/contact' %>

<% page_title "Contact Us" %>

<div class="contact col-md-12 col-sm-12 col-xs-12 no-padding">

  <h2 class="white border"><a>Get in Touch</a></h2>
  <div class="contact-block-right col-md-12 col-sm-12 col-xs-12 no-padding white-back" id="boot-camp">
    <div class="container no-padding">
      <div class="row no-margin">

        <div class="contact-content col-md-12 col-sm-12 col-xs-12">
          <p>Our Engineers at Katomaran Robotics tend to inspire people not by showing things, but by doing things. Pop in to say a hello to our engineers or get in touch to get clarified about your queries or concerns.</p>

          <div class="workshop-interest-block col-md-12 col-sm-12 col-xs-12 no-padding">
            <h6 class="underline"> Interested in organizing a workshop with us</h6>
            <p>Please fill out the quote form from <a href="/quote">here. </a> Our Engineers will reach you.</p>
            <p>We offer a customized workshop plan based on your curriculum. Give it a try, we promise that you will not be disappointed</p>
          </div>

          <div class="address-block col-md-12 col-sm-12 col-xs-12 no-padding">
            <h6 class="underline">Here are the places to find us </h6>

            <ul>
              <li>
                <i class="fa fa-phone" aria-hidden="true"></i>
                +91 - 8754 933700
              </li>
              <li>
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                robotics@katomaran.com
              </li>
              <li>
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                15, Harsha Gardens, Machampalayam, Sundarapuram, Coimbatore, Tamilnadu, India - 641024
              </li>
            </ul>
          </div>

          <div class="social-media-block col-md-12 col-sm-12 col-xs-12 no-padding">
            <h6 class="underline">Our Social Presences </h6>
            <p>Pop in say a hello.</p>
            <ul class="social-media col-md-12 col-sm-12 col-xs-12 no-padding">
              <li class="col-md-4 col-sm-4 col-xs-12 no-padding">
                <a href="<%= get_social_link(:facebook) %>">
                  <i class="fa fa-facebook" aria-hidden="true"></i>
                </a>
              </li>
              <li class="col-md-4 col-sm-4 col-xs-12 no-padding">
                <a href="<%= get_social_link(:twitter) %>">
                  <i class="fa fa-twitter" aria-hidden="true"></i>
                </a>
              </li>
              <li class="col-md-4 col-sm-4 col-xs-12 no-padding">
                <a href="<%= get_social_link(:google) %>">
                  <i class="fa fa-google-plus" aria-hidden="true"></i>
                </a>
              </li>
            </ul>
          </div>

          <div class="map-block col-md-12 col-sm-12 col-xs-12">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3917.1270406560952!2d76.96551031480236!3d10.953774992201298!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTDCsDU3JzEzLjYiTiA3NsKwNTgnMDMuNyJF!5e0!3m2!1sen!2sin!4v1477203173445" width="100%" height="500" frameborder="0" style="border:0" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/downloads.html.erb
<%#= stylesheet_link_tag 'site/service' %>

<% page_title "Our Downloads" %>

<div class="downloads col-md-12 col-sm-12 col-xs-12 no-padding">

  <h2 class="white border"><a>Our Downloads</a></h2>
  <div class="download-block col-md-12 col-sm-12 col-xs-12 no-padding white-back">
    <div class="container no-padding">
      <div class="row no-margin">

        <% @assets.each do |asset| %>
            <div class="download-content col-md-3 col-sm-4 col-xs-6 no-padding">
              <a href="<%= "/download/#{asset.alias_name}" %>">
                <img src="/images/core/<%= get_file_img(asset.get_file_type) %>" class="preview_icon"/>
                <p><%= asset.title %></p>
              </a>
            </div>
        <% end %>

      </div>
    </div>
  </div>
</div>


<style>
    .download-content .preview_icon {
        max-width: 75%;
    }
    .download-content{
        text-align: center;
        padding: 3%;
    }
    .download-content p{
        padding: 5%;
    }
</style>

app/views/home/events_list.html.erb
<%#= stylesheet_link_tag 'site/service' %>

<% page_title "Events" %>

<div class="events col-md-12 col-sm-12 col-xs-12 no-padding">

  <h2 class="white border"><a>Our Events</a></h2>
  <div class="event-block col-md-12 col-sm-12 col-xs-12 no-padding white-back">
    <div class="container no-padding">
      <div class="row no-margin">

        <div class="event-block col-md-12 col-sm-12 col-xs-12 no-padding">
          <div class="container no-padding">
            <div class="row no-margin">

              <div class="event-content col-md-12 col-sm-12 col-xs-12">

                <div class="img-block col-md-5 col-sm-12 col-xs-12 no-padding">
                  <img src="/images/aayudh.jpeg">
                </div>

                <div class="text-block col-md-7 col-sm-12 col-xs-12 no-padding">
                  <h4>AAYUDH'16</h4>
                  <p>Aayudh is the annual Robotic competition conducted by Katomaran Robotics. Stepping on its inaugural edition, Aayudh aims on laying the basic platform for the upcoming generation of Engineers to exhibit their skills on stuff that works without man power.</p>
                  <a href="/download/aayudh'16-ps" title="Aayudh-problem-statement.pdf"><span>Download Problem Statement</span></a>
                </div>

              </div>

            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>


<style>
    .event-content{
        padding: 3%;
    }
    .img-block img{
        max-width: 90%;
    }
    .text-block a{
        float: right;
    }
</style>

app/views/home/history.html.erb
<div class="container-block col-md-12 col-sm-12 col-xs-12 no-padding">
  <div class="summary-block col-md-12 col-sm-12 col-xs-12 no-padding">
    <div class="container no-padding">
      <div class="row no-margin">

        <div class="content col-md-12 col-sm-12 col-xs-12 no-padding">
          <h3 class="title"><a>Under Construction</a></h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= stylesheet_link_tag "site/home" %>
<%= javascript_include_tag "site/home" %>

<script type="text/javascript" src="fresco/js/fresco.js"></script>
<link rel="stylesheet" href="fresco/css/fresco.css">


<div class="intro col-md-12 col-sm-12 col-xs-12 no-padding">

  <h2 class="white border"><a>Our Intro</a></h2>

  <div class="col-md-12 col-sm-12 col-xs-12 no-padding">
    <div class="container no-padding">
      <div class="row no-margin">

        <div class="intro-content col-md-12 col-sm-12 col-xs-12">
          <p>
            A training invite to induce innovation among the budding engineers of our nation. Inspiring students to sharpen their skills by spending some precious time with the trainers of Katomaran Robotics remains the motive of this event. We provide loads of theories, knowledge, industrial updates and more to guide our students to generate befitting thoughts. But as known, innovation is not complete only with creative ideas and it needs something more to evolve into its ultimate form, which in this case is transfiguring the ideas into reality. Here comes the justification why we lead all our customers to get involved with hardware. Exposing to various parts of an Artificially Intelligent Species beginning from a small plastic screw and terminating at a completely integrated Robot not only improves the mastery of our students but also makes us, Katomaran Engineered Trainers to own a lot of Pride in what we do. By the end of the day, we intend to motivate students to grow better and better so that they can be proficient than the generation we know and take our nation to greater heights.
          </p>
          <hr>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="services col-md-12 col-sm-12 col-xs-12 no-padding">

  <h2 class="white border"><a>What we offer</a></h2>

  <% block=["left", "right"] %>
  <% @services.each_with_index do |article, index| %>
      <div class="service-block-<%= block[index%2] %> col-md-12 col-sm-12 col-xs-12 no-padding">
        <div class="container no-padding">
          <div class="row no-margin">

            <div class="services-content col-md-12 col-sm-12 col-xs-12">

              <div class="img-block col-md-4 col-sm-12 col-xs-12 no-padding">
                <!--<img src="/images/1.jpg">-->
                <i class="fa <%= article.image_url %> fa-lg fa1"></i>
              </div>

              <div class="text-block col-md-8 col-sm-12 col-xs-12 no-padding">
                <h4><%= article.title %></h4>
                <p><%= article.description %></p>
                <div class="know-more-button">
                  <%= custom_link_3("Know More", article.alias_url, "link-3") %>
                </div>
              </div>

            </div>

          </div>
        </div>
      </div>
  <% end %>

  <div class="servies-query col-md-12 col-sm-12 col-xs-12 no-padding gray-back">
    <div class="container no-padding">
      <div class="row no-margin">
        <div class="query-content">
          <h4>Need More Info...?</h4>
          <p>Try to get in touch with our engineers. We will clarify your queries.</p>
          <a href="/contact-us">
            <span></span>
            <span></span>
          </a>
        </div>
      </div>
    </div>
  </div>

</div>

<div class="showcase col-md-12 col-sm-12 col-xs-12 no-padding" style="display: <%= @gallery.blank? ? "none" : "auto" %>">

  <h2 class="white border"><a>Our Show-Case</a></h2>
  <div class="showcase-block col-md-12 col-sm-12 col-xs-12 no-padding">
    <div class="container no-padding">
      <div class="row">

        <div class="grid">

          <% @gallery.each do |gallery| %>
              <div class="showcase-content col-md-12 col-sm-12 col-xs-12" id="first">
                <div class="figure col-md-5 col-sm-5 col-xs-12 img-block no-padding">
                  <figure class="effect-sadie">
                    <%= image_tag(gallery.title_image.location_path, alt:gallery.title_image.title) %>
                    <figcaption>
                      <p><%= gallery.title_image.caption %></p>
                      <a data-fresco-group="<%= gallery.name %>" data-fresco-caption="<%= gallery.caption %>" class="fresco" href="<%= gallery.title_image.location_path %>"></a>
                    </figcaption>
                  </figure>
                </div>
                <div class="content col-md-7 col-sm-7 col-xs-12 img-block no-padding">
                  <h4><%= gallery.name.upcase %></h4>
                  <p><%= gallery.description %></p>
                </div>
                <div class="all-images col-md-7 col-sm-7 col-xs-12 img-block no-padding">

                  <% gallery.images_without_title_image.by_sequence.limit(3).each do |image| %>
                      <div class="figure img-block no-padding">
                        <figure class="effect-sadie">
                          <%= image_tag(image.location_path, alt:image.title) %>
                          <figcaption>
                            <p><%= image.caption %></p>
                            <a data-fresco-group="<%= gallery.name %>" data-fresco-caption="<%= gallery.caption %>" class="fresco" href="<%= image.location_path %>"></a>
                          </figcaption>
                        </figure>
                      </div>
                  <% end %>

                </div>
              </div>
          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>

<div class="newsletter col-md-12 col-sm-12 col-xs-12 no-padding" id="newsletters">
  <div class="container no-padding">
    <div class="row">

      <div class="newsletter-block col-md-12 col-sm-12 col-xs-12 no-padding">
        <h2 class="border white"><a>Pop-in to our Mailing List</a></h2>
        <p>We'll send occassional email with updates and many more interesting stuffs. You can unsubscribe at any time.</p>

        <div class="col-md-12 col-sm-12 col-xs-12 no-padding">

          <%= form_tag add_to_newsletter_path, id: "add_to_newsletter" do %>
              <p class="text-fiel col-md-8 col-sm-8 col-xs-12 no-padding">
                <%= text_field_tag :email, nil, class: "form-white", placeholder: "Email" %>
              </p>

              <%= hidden_field_tag :news_id, @newsletter.try(:id) %>

              <div class="submit col-md-4 col-sm-4 col-xs-12 no-padding">
                <%= custom_button_3(value:"Get into the Queue") %>
              </div>
              <div class="validation">
                <img src="http://i.imgur.com/HC3a6u3.gif">
                <p>
                  <i class="fa fa-check-circle" aria-hidden="true"></i>
                  <i class="fa fa-times-circle" aria-hidden="true"></i>
                  <span> </span>
                </p>
              </div>
          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>


<div class="popup">
  <button type="button" class="btn btn-info btn-lg pop_up_button" data-toggle="modal" data-target="#myModal" style="display: none;">Show PopUp</button>
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Interested in Aayudh'16..!!!</h4>
        </div>
        <div class="modal-body">
          <p>Aayudh is the annual Robotic competition conducted by Katomaran Robotics. <a href="/events">Click Here</a> to know more about our events...</p>
          <p><a href="/#newsletters" onclick="$('.popup .modal-footer button').trigger('click')">Sign-up</a> for our newsletter to get info at your inbox.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

</div>



<style>
    .validation {
        float: left;
        font-size: 15px;
        padding-top: 1%;
        text-align: center;
        width: 100%;
    }
    .validation p{
        display: inline;
    }
    .validation > img {
        display: inline-block;
        max-width: 75px;
        visibility: hidden;
    }
    .validation p i{
        padding-right: 1%;
        display: none;
    }
    .validation p.true{
        color: green;
    }
    .validation p.false{
        color: red;
    }
    .validation p.true i.fa-check-circle{
        display: inline;
    }
    .validation p.false i.fa-times-circle{
        display: inline;
    }
    .newsletter{
        /*background-color: #59abe3;*/
        background-image: url('http://www.oneboardpc.com/wp-content/uploads/2016/03/Background.jpg');
        background-size: 100% auto ;
    }
    .submit button{
        margin: 0;
        display: inline;
        float: left;
    }
    .newsletter-block form p{
        text-align: center;
        padding-right: 3%;
        margin: 0.5% 0;
    }
    .newsletter-block p input{
        width: 75%;
        display: inline;
        float: right;
        height: 50px;
        background-color: transparent;
    }
    .newsletter-block{
        margin: 1% 0 5%;
        text-align: center;
    }
    .newsletter-block .text-field input{
        width: 75%;
    }
    .showcase-content{
        position: relative;
        overflow: hidden;
    }
    .showcase-content .content {
        padding-top: 10%;
        text-align: center;
        transition:all 0.4s linear 0s;
    }
    .showcase-content:hover .content{
        padding: 1%;
    }
    .showcase-content:hover .all-images{
        bottom: 0;
    }
    .showcase-content .all-images {
        bottom: -90%;
        right: 0;
        position: absolute;
        transition: all 0.4s linear 0s;
    }
    .all-images .effect-sadie p {
        font-size: 10px;
    }
    .all-images figure {
      max-width: 33%;
      margin: 0.1%;

    }
</style>

app/views/home/list_blog.html.erb
<%= stylesheet_link_tag 'site/blog' %>
<div class="blogs col-md-12 col-sm-12 col-xs-12 no-padding">

  <h2 class="white border"><a>Our Blog</a></h2>
  <div class="container no-padding">
    <div class="row no-margin">

      <div class="blog col-md-12 col-sm-12 col-xs-12">

        <div class="blog-content col-md-4 col-sm-6 col-xs-12">
          <h4>Article Title</h4>
          <p>this is the test descriptionf ro teadf safas safas sffasfvdasff asf asfs asfqrsda as s</p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/home/quote.html.erb
<%#= stylesheet_link_tag 'site/service' %>

<% page_title "Request Quote" %>

<div class="quote col-md-12 col-sm-12 col-xs-12 no-padding">

  <h2 class="white border"><a>Request A Quote</a></h2>
  <div class="quote-block-right col-md-12 col-sm-12 col-xs-12 no-padding white-back">
    <div class="container no-padding">
      <div class="row no-margin">

        <%= form_tag submit_quote_path do %>

            <p class="col-md-2 col-sm-4 col-xs-12 text-field">
              <%= text_field_tag 'quote[name]', nil, {:class => 'form-white', :placeholder => 'Sequence Number'} %>
            </p>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/services.html.erb
<%= stylesheet_link_tag 'site/service' %>

<% page_title "Our Services" %>

<div class="services col-md-12 col-sm-12 col-xs-12 no-padding">

  <h2 class="white border"><a>Our Services</a></h2>
  <div class="service-block-right col-md-12 col-sm-12 col-xs-12 no-padding white-back" id="boot-camp">
    <div class="container no-padding">
      <div class="row no-margin">

        <div class="services-content col-md-12 col-sm-12 col-xs-12">

          <div class="img-block col-md-4 col-sm-12 col-xs-12 no-padding">
            <!--<img src="/images/1.jpg">-->
            <i class="fa fa-cube fa-lg fa1"></i>
          </div>
          <div class="text-block">
            <h4>BootCamps</h4>
            <p>A Bootcamp is a short term training programme. The duration of this event might vary between 2 to 5 days based on the demand of our students and the content of the formulated course. Students can opt to join our Bootcamp by either enrolling themselves with the register button that we have in a random space of our website or by associating with the Hosting management. Camp schedules are continuously updated on our website and regarding data can be gathered by frequently visiting this online location. In this event, students are split into multiple teams of equal strength both physically and mentally. Katomaran trainers will provide the students, the theories, statistics and data on the concerned programme and the students are anticipated to travel a journey where they listen, see, visualize and implement Robotics with some support that they gain from electronic hardware provided. Competitive nature of our events makes the journey more interesting and at the end of this event, students start waiting for our next event to start again. We also understand that students hate to attend trainings on Sundays and try to keep Sundays out of our schedules, although this is not a commitment.</p>
            <p>So students, Check us first before checking on Google if you are interested to learn Robotics.</p>
            <h5>Formulated Courses</h5>
            <ul>
              <li>Embedded Hands-on Workshop - Basic ( <a href="/download/second" title="Embedded-basic.pdf"><span>Download Package</span></a> )</li>
              <li>Embedded Hands-on Workshop - Advanced ( <a href="/download/advanced" title="Embedded-advanced.pdf"><span>Download Package</span></a> )</li>
            </ul>
            <h6 class="underline">Embedded Hands-on Workshop - Basic</h6>
            <p>A Bootcamp is a short term training programme. The duration of this event might vary between 2 to 5 days based on the demand of our students and the content of the formulated course. Students can opt to join our Bootcamp by either enrolling themselves with the register button that we have in a random space of our website or by associating with the Hosting management. Camp schedules are continuously updated on our website and regarding data can be gathered by frequently visiting this online location. In this event, students are split into multiple teams of equal strength both physically and mentally. Katomaran trainers will provide the students, the theories, statistics and data on the concerned programme and the students are anticipated to travel a journey where they listen, see, visualize and implement Robotics with some support that they gain from electronic hardware provided. </p>
            <h6 class="underline">Embedded Hands-on Workshop - Advanced</h6>
            <p>A Bootcamp is a short term training programme. The duration of this event might vary between 2 to 5 days based on the demand of our students and the content of the formulated course. Students can opt to join our Bootcamp by either enrolling themselves with the register button that we have in a random space of our website or by associating with the Hosting management. Camp schedules are continuously updated on our website and regarding data can be gathered by frequently visiting this online location. In this event, students are split into multiple teams of equal strength both physically and mentally. Katomaran trainers will provide the students, the theories, statistics and data on the concerned programme and the students are anticipated to travel a journey where they listen, see, visualize and implement Robotics with some support that they gain from electronic hardware provided. </p>

          </div>

        </div>

      </div>
    </div>
  </div>

  <div class="service-block-left col-md-12 col-sm-12 col-xs-12 no-padding gray-back" id="foundation">
    <div class="container no-padding">
      <div class="row no-margin">

        <div class="services-content col-md-12 col-sm-12 col-xs-12">

          <div class="img-block col-md-4 col-sm-12 col-xs-12 no-padding">
            <!--<img src="/images/1.jpg">-->
            <i class="fa fa-cube fa-lg fa1"></i>
          </div>
          <div class="text-block">
            <h4>Foundations</h4>
            <p>A Foundation is a long-term Laboratory-type training programme. The duration of this might vary between 4 to 6 months based on the demand of Hosting Management and the content of the formulated course. Students can opt for a Foundation only by associating with the Hosting Management and outsiders are strictly not allowed to participate in this event. Foundation is a kind of regular laboratory classes run in schools and colleges. Amounts of syllabus for the course and hours to be handled are pre-planned by Katomaran Robotics in agreement with the Hosting Management before the start of this long term activity. Schedule for the event will be released only by the Hosting Management. Students can still collect data on the ongoing foundation by checking our website. Katomaran Trainers will become a part of every attendee's academic life by connecting with them at regular intervals of time and causing them to build a vast variety of Robotics projects under numerous domains which can be further developed into efficiency yielding applications. Students become individualistic in such events boosting their confidence and build their own robots accepting all credits on their own. We not only teach students to build robots but also the skill of building them fast so that they can be competent in any environment they are pushed into in their future. </p>
            <p>We know that traditional Lab classes are sometimes boring and there is one thing we can assure from our side; we are not Old School.</p>
            <h5>Formulated Courses</h5>
            <ul>
              <li>Embedded Hands-on Workshop - Basic ( <a href="/download/second" title="Embedded-basic.pdf"><span>Download Package</span></a> )</li>
              <li>Embedded Hands-on Workshop - Advanced ( <a href="/download/advanced" title="Embedded-advanced.pdf"><span>Download Package</span></a> )</li>
            </ul>
            <h6 class="underline">Embedded Hands-on Workshop - Basic</h6>
            <p>A Bootcamp is a short term training programme. The duration of this event might vary between 2 to 5 days based on the demand of our students and the content of the formulated course. Students can opt to join our Bootcamp by either enrolling themselves with the register button that we have in a random space of our website or by associating with the Hosting management. Camp schedules are continuously updated on our website and regarding data can be gathered by frequently visiting this online location. In this event, students are split into multiple teams of equal strength both physically and mentally. Katomaran trainers will provide the students, the theories, statistics and data on the concerned programme and the students are anticipated to travel a journey where they listen, see, visualize and implement Robotics with some support that they gain from electronic hardware provided. </p>
            <h6 class="underline">Embedded Hands-on Workshop - Advanced</h6>
            <p>A Bootcamp is a short term training programme. The duration of this event might vary between 2 to 5 days based on the demand of our students and the content of the formulated course. Students can opt to join our Bootcamp by either enrolling themselves with the register button that we have in a random space of our website or by associating with the Hosting management. Camp schedules are continuously updated on our website and regarding data can be gathered by frequently visiting this online location. In this event, students are split into multiple teams of equal strength both physically and mentally. Katomaran trainers will provide the students, the theories, statistics and data on the concerned programme and the students are anticipated to travel a journey where they listen, see, visualize and implement Robotics with some support that they gain from electronic hardware provided. </p>

          </div>

        </div>

      </div>
    </div>
  </div>

  <div class="service-block-right col-md-12 col-sm-12 col-xs-12 no-padding white-back" id="r&d">
    <div class="container no-padding">
      <div class="row no-margin">

        <div class="services-content col-md-12 col-sm-12 col-xs-12">

          <div class="img-block col-md-4 col-sm-12 col-xs-12 no-padding">
            <!--<img src="/images/1.jpg">-->
            <i class="fa fa-cube fa-lg fa1"></i>
          </div>
          <div class="text-block">
            <h4>R & D</h4>
            <p>Research and Development is the ultimate destination of Katomaran Robotics. R&D department is targeted towards generating innovative ideas from young Engineers, examining them and evolving some of the valid ideas into reality. Engineers of Katomaran Robotics share their knowledge and experience in R&D to the Interns of Katomaran and direct them towards a proper path. This wing of Katomaran robotics is still being established and interested candidates are requested to get in touch with Katomaran Robotics team to get more data concerning R&D. </p>
          </div>

        </div>

      </div>
    </div>
  </div>
</div>