config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :admin do
    resources :articles do
      get 'new_category', on: :collection
      get 'new_tag', on: :collection
      post 'create_category', on: :collection
      post 'create_tag', on: :collection
    end
    resources :assets
    resources :reports do
      get 'download'
      post 'download_file'
    end
  end

  resources :admin do
    get 'dashboard', on: :collection
    get 'reports', on: :collection
    get 'upload', on: :collection
    post 'save_asset', on: :collection
  end

  get '/our-services' => 'home#services', :as => 'services'
  get '/show-case' => 'home#show_case', :as => 'show_case'
  get '/history' => 'home#history', :as => 'history'
  get '/contact-us' => 'home#contact_us', :as => 'contact_us'
  get '/downloads' => 'home#downloads', :as => 'downloads'
  get '/events' => 'home#events_list', :as => 'events_list'
  get '/events/aayudh' => 'home#event_show', :as => 'event_show'

  get '/quote' => 'home#quote', :as => 'quote_form'
  post 'submit_quote' => 'home#submit_quote', :as => 'submit_quote'

  get '/download/:alias_name(/:access_code)' => "home#get_file"

  get '/login' => 'home#login', :as => 'login' #needs to be changed

  post '/home/add_to_newsletter', :as => 'add_to_newsletter'

  get 'blog/articles' => 'blog#list_blog', as: "list_blog_articles"
  get 'blog/articles/:article_alias_name' => 'blog#show_blog', as: "blog_article"
  get 'blog/categories/:category_alias_name' => 'blog#category_articles', as: "category_articles"
  get 'blog/tag/:tag_alias_name' => 'blog#tag_articles', as: "tag_articles"

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  include ArticlesHelper

  before_action :right_components, only: ['list_blog', 'tag_articles', 'category_articles']

  def list_blog
    @articles=Article.published_blog
    @page_properties.merge!(page_properties_for("list_blog"))
  end

  def show_blog
    @article=Article.published_blog.find_by_alias_url(params[:article_alias_name])
    render_404 and return if @article.blank?
    @page_properties.merge!(page_properties_for("show_blog"))
    @article_content=@article.article_content
  end

  def tag_articles
    @page_properties.merge!(page_properties_for("tag_articles"))
    @tag=Tag.find_by_alias_name(params[:tag_alias_name])
    render_404 and return if @tag.blank?
    @articles=Article.published_blog.by_tag(@tag.id)
  end

  def category_articles
    @page_properties.merge!(page_properties_for("category_articles"))
    @category=Category.find_by_alias_name(params[:category_alias_name])
    render_404 and return if @category.blank?
    @articles=Article.published_blog.by_category(@category.id)
  end

  private

  def right_components
    @categories=Category.by_active
    @right_articles=Article.published_blog
  end
end

app/helpers/blog_helper.rb
module BlogHelper

  def get_next_article(article_id)
    ids=Article.published_blog.by_sequence.map(&:id)
    id=ids.index(article_id).to_i+1
    id = id>=ids.length ? id-ids.length : id
    Article.find(ids[id])
  end

  def get_prev_article(article_id)
    ids=Article.published_blog.by_sequence.map(&:id)
    id=ids.index(article_id).to_i-1
    id = id>=ids.length ? id-ids.length : id
    Article.find(ids[id])
  end

end

app/views/blog/_content_block.html.erb
<div class="blog-left col-md-9 col-sm-9 col-xs-12">

  <% @articles.each do |article| %>
      <div class="blog-content col-md-12 col-sm-12 col-xs-12">
        <p class="blog-details">
          <span class="category"><a href="<%= category_articles_path(category_alias_name: article.category.alias_name) rescue nil %>"><%= article.category.try(:name) %></a></span>
          Posted by: <span><%= article.author %></span><%= ", " + distance_of_time_in_words(Time.now, article.display_date).to_s + " ago" rescue nil %>
        </p>
        <h4>
          <a href="<%= blog_article_path(article_alias_name: article.alias_url) %>"><%= article.title %></a>
        </h4>
        <p><%= article.description %></p>
      </div>
  <% end %>

</div>

app/views/blog/_right_component.html.erb
<div class="blog-right col-md-3 col-sm-3 col-xs-12">
  <div class="blog-categories col-md-12 col-sm-12 col-xs-12">
    <h5>Categories</h5>
    <ul>
      <% @categories.each do |category|%>
          <li>
            <a href="<%= category_articles_path(category_alias_name: category.alias_name)%>"><%= category.name %></a>
          </li>
      <% end %>
    </ul>
  </div>

  <!--<div class="blog-recent col-md-12 col-sm-12 col-xs-12">
    <h5>Recent Posts</h5>
    <ul>
      <li><a href="#">testing</a></li>
      <li><a href="#">testing</a></li>
      <li><a href="#">testing</a></li>
    </ul>
  </div>-->

  <div class="blog-related col-md-12 col-sm-12 col-xs-12">
    <h5>Editor's Pick</h5>
    <ul>
      <% @right_articles.each do |article| %>
          <li>
            <a href="<%= blog_article_path(article_alias_name: article.alias_url) %>">
              <%= article.title %>
            </a>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/blog/category_articles.html.erb
<%= stylesheet_link_tag 'site/blog' %>

<div class="blogs col-md-12 col-sm-12 col-xs-12 no-padding">

  <h2 class="white border"><a>Category - <%= @category.name %></a></h2>
  <div class="container no-padding">
    <div class="row no-margin">

      <div class="blog col-md-12 col-sm-12 col-xs-12">

        <%= render 'content_block' %>

        <%= render 'right_component' %>

      </div>
    </div>
  </div>
</div>

app/views/blog/list_blog.html.erb
<%= stylesheet_link_tag 'site/blog' %>

<% page_title "Our Blog" %>

<div class="blogs col-md-12 col-sm-12 col-xs-12 no-padding">

  <h2 class="white border"><a>Our Blog</a></h2>
  <div class="container no-padding">
    <div class="row no-margin">

      <div class="blog col-md-12 col-sm-12 col-xs-12">

        <%= render 'content_block' %>

        <%= render 'right_component' %>

      </div>

    </div>
  </div>
</div>

app/views/blog/show_blog.html.erb
<%= stylesheet_link_tag 'site/blog' %>

<% page_title(@article.page_title) %>
<% meta_tag :description, @article.meta_description %>
<% meta_tag :keywords, @article.meta_keywords %>

<div class="blogs col-md-12 col-sm-12 col-xs-12 no-padding">

  <h2 class="white border"><a><%= @article.title %></a></h2>
  <div class="blogs col-md-12 col-sm-12 col-xs-12 no-padding white-back">
    <div class="container no-padding">
      <div class="row no-margin">

        <div class="blog-content col-md-12 col-sm-12 col-xs-12">
          <%= raw @article_content.content %>
        </div>

        <div class="pagination col-md-12 col-sm-12 col-xs-12 no-padding">
          <div class="left-pagination col-md-6 col-sm-6 col-xs-12">
            <% prev_article = get_prev_article(@article.id) %>
            <span>Prev Article</span>
            <h6><a href="<%= blog_article_path(article_alias_name: prev_article.alias_url) %>"><%= prev_article.title %></a></h6>
          </div>

          <div class="right-pagination col-md-6 col-sm-6 col-xs-12">
            <% next_article = get_next_article(@article.id) %>
            <span>Next Article</span>
            <h6><a href="<%= blog_article_path(article_alias_name: next_article.alias_url) %>"><%= next_article.title %></a></h6>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blog/tag_articles.html.erb
<%= stylesheet_link_tag 'site/blog' %>

<div class="blogs col-md-12 col-sm-12 col-xs-12 no-padding">

  <h2 class="white border"><a>Tag - <%= @tag.name %></a></h2>
  <div class="container no-padding">
    <div class="row no-margin">

      <div class="blog col-md-12 col-sm-12 col-xs-12">

        <%= render 'right_component' %>
        
        <%= render 'right_component' %>

      </div>

    </div>
  </div>
</div>