config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  namespace :admin do
    resources :articles do
      get 'new_category', on: :collection
      get 'new_tag', on: :collection
      post 'create_category', on: :collection
      post 'create_tag', on: :collection
    end
    resources :assets
    resources :reports do
      get 'download'
      post 'download_file'
    end
  end

  resources :admin do
    get 'dashboard', on: :collection
    get 'reports', on: :collection
    get 'upload', on: :collection
    post 'save_asset', on: :collection
  end

  get '/our-services' => 'home#services', :as => 'services'
  get '/show-case' => 'home#show_case', :as => 'show_case'
  get '/history' => 'home#history', :as => 'history'
  get '/contact-us' => 'home#contact_us', :as => 'contact_us'
  get '/downloads' => 'home#downloads', :as => 'downloads'
  get '/events' => 'home#events_list', :as => 'events_list'
  get '/events/aayudh' => 'home#event_show', :as => 'event_show'

  get '/quote' => 'home#quote', :as => 'quote_form'
  post 'submit_quote' => 'home#submit_quote', :as => 'submit_quote'

  get '/download/:alias_name(/:access_code)' => "home#get_file"

  get '/login' => 'home#login', :as => 'login' #needs to be changed

  post '/home/add_to_newsletter', :as => 'add_to_newsletter'

  get 'blog/articles' => 'blog#list_blog', as: "list_blog_articles"
  get 'blog/articles/:article_alias_name' => 'blog#show_blog', as: "blog_article"
  get 'blog/categories/:category_alias_name' => 'blog#category_articles', as: "category_articles"
  get 'blog/tag/:tag_alias_name' => 'blog#tag_articles', as: "tag_articles"

end

app/views/layouts/_admin_footer.html.erb
<footer>
  <div class="footer-content col-md-12 col-sm-12 col-xs-12 no-padding">
    <div class="container no-padding">
      <div class="row no-margin">

        <div class="footer-top col-md-12 col-sm-12 col-xs-12 no-padding">
          <ul>
            <li><a href="<%= login_path %>">Login</a></li>
            <li><a href="<%= downloads_path %>">Downloads</a></li>
            <li><a href="/faq">FAQ</a></li>
            <li><a href="/quote">Request Quote</a></li>
            <li><a href="/blog/articles">Our Blog</a></li>
            <li><a href="/projects">Projects</a></li>
          </ul>
        </div>

        <div class="footer-bottom col-md-12 col-sm-12 col-xs-12 no-padding">
          <div class="copy-right">
            <p>&copy; <%= Date.today.strftime("%Y") %>. Katomaran Techno Solutions. </p>
            <p>Powered by - <a href="http://www.webservices.katomaran.com" class="tip">Katomaran WebServices</a></p>
          </div>
          <div class="social-icon">
            <a href="<%= get_social_link(:facebook) %>">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="<%= get_social_link(:twitter) %>">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a href="<%= get_social_link(:google) %>">
              <i class="fa fa-google-plus" aria-hidden="true"></i>
            </a>
          </div>
        </div>

      </div>

    </div>
  </div>
</footer>

app/views/layouts/_admin_header.html.erb
<header>
  <div class="banner">
    <div class="header-content col-md-12 col-sm-12 col-xs-12 no-padding">
      <div class="container no-padding">
        <div class="row no-margin">

          <div class="header-top col-md-12 col-sm-12 col-xs-12">
            <div class="header-left col-md-3 col-sm-3 col-xs-12 no-padding">
              <div class="header-logo">
                <a href="/"><img src="/images/core/menu_logo.png"/></a>
              </div>
            </div>

            <div class="header-right col-md-9 col-sm-9 col-xs-12 no-padding">
              <div class="header-menu">

                <section class="menu">
                  <nav class="cl-effect-9 text-right">
                    <a href="<%= dashboard_admin_index_path %>"><span>Dashboard</span><span>Get all controls</span></a>
                    <a href="<%= admin_articles_path %>"><span>Articles</span><span>See all articles</span></a>
                    <a href="<%= reports_admin_index_path %>"><span>Reports</span><span>Get the Status</span></a>
                    <a href="<%= admin_assets_path %>"><span>Upload</span><span>Manage Assets</span></a>
                    <a href="<%= root_path %>"><span>Visit Site</span><span>Our World</span></a>

                  </nav>
                </section>

              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_site_footer.html.erb
<footer>
  <div class="footer-content col-md-12 col-sm-12 col-xs-12 no-padding">
    <div class="container no-padding">
      <div class="row no-margin">

        <div class="footer-top col-md-12 col-sm-12 col-xs-12 no-padding">
          <ul>
            <li><a href="<%= login_path %>">Login</a></li>
            <li><a href="<%= downloads_path %>">Downloads</a></li>
            <li><a href="/faq">FAQ</a></li>
            <li><a href="/quote">Request Quote</a></li>
            <li><a href="/blog/articles">Our Blog</a></li>
            <li><a href="/projects">Projects</a></li>
          </ul>
        </div>

        <div class="footer-bottom col-md-12 col-sm-12 col-xs-12 no-padding">
          <div class="copy-right">
            <p>&copy; <%= Date.today.strftime("%Y") %>. Katomaran Techno Solutions. </p>
            <p>Powered by - <a href="http://www.webservices.katomaran.com" class="tip">Katomaran WebServices</a></p>
          </div>
          <div class="social-icon">
            <a href="<%= get_social_link(:facebook) %>">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="<%= get_social_link(:twitter) %>">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a href="<%= get_social_link(:google) %>">
              <i class="fa fa-google-plus" aria-hidden="true"></i>
            </a>
          </div>
        </div>

      </div>

    </div>
  </div>
</footer>

app/views/layouts/_site_header.html.erb
<header>
<div class="banner">
  <div class="header-content col-md-12 col-sm-12 col-xs-12 no-padding">
    <div class="container no-padding">
      <div class="row no-margin">

        <div class="header-top col-md-12 col-sm-12 col-xs-12 no-padding">
          <div class="header-left col-md-3 col-sm-3 col-xs-9 no-padding">
            <div class="header-logo">
              <a href="/"><img src="/images/core/menu_logo.png"/></a>
            </div>
          </div>

          <div class="header-right col-md-9 col-sm-9 col-xs-3 no-padding">
            <div class="header-menu">

              <section class="menu">
                <nav class="cl-effect-9 text-right">
                  <a href="<%= root_path %>">
                    <span>Home</span>
                    <span>Our World</span>
                  </a>
                  <a href="<%= services_path %>">
                    <span>Services</span>
                    <span>Our Expertize</span>
                  </a>
                  <a href="<%= show_case_path %>">
                    <span>Showcase</span>
                    <span>Pictures Speak</span>
                  </a>
                  <!--<a href="<%#= history_path %>">
                    <span>History</span>
                    <span>Our Timeline</span>
                  </a>-->
                  <a href="<%= events_list_path %>">
                    <span>Events</span>
                    <span>Make it Big</span>
                  </a>
                  <a href="<%= contact_us_path %>">
                    <span>Contact Us</span>
                    <span>Get in Touch</span>
                  </a>
                </nav>
              </section>

            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
</header>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Katomaran Robotics Admin Panel</title>
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">-->
  <!--<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >-->

<meta charset="UTF-8">
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <meta name="google-site-verification" content="Bi9RrRAR7drDCVv1gcXbP1Ge0CrSPilZfJn7lpjWg88" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=2.0,minimum-scale=1.0" />

  <!-- Google fonts -->
  <!-- <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'> -->

  <link rel="stylesheet" href="/offline_assets/bootstrap.min.css">
  <link rel="script" href="/offline_assets/bootstrap.min.js">
  <link rel="stylesheet" href="/offline_assets/font-awesome.min.css">
  <link rel="script" href="/offline_assets/jquery-1.11.1.js">

  <%= stylesheet_link_tag 'admin', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>


</head>
<body>
<%= render 'layouts/admin_header' %>

<%= yield %>

<%= render 'layouts/admin_footer' %>

</body>
<script>
    $(window).resize(function(){ SetHalfPageBanner(); });
    $(window).load(function(){ SetHalfPageBanner(); });

    // select box script
    (function () {
        [].slice.call(document.querySelectorAll('select.cs-select')).forEach(function (el) {
            new SelectFx(el);
        });
    })();
</script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= yield_page_title %>

  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">-->
  <!--<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >-->

  <%= yield_meta_tag(:title) %>
  <%= yield_meta_tag(:keywords) %>
  <%= yield_meta_tag(:description) %>

<meta charset="UTF-8">
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <meta name="google-site-verification" content="Bi9RrRAR7drDCVv1gcXbP1Ge0CrSPilZfJn7lpjWg88" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=2.0,minimum-scale=1.0" />

  <!-- Google fonts -->
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans|Poiret+One|Josefin+Sans:400,600|Questrial|Catamaran:400,500' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">
  <!-- -->

  <link rel="stylesheet" href="/offline_assets/bootstrap.min.css">
  <link rel="stylesheet" href="/offline_assets/bootstrap.min.js">
  <link rel="stylesheet" href="/offline_assets/font-awesome.min.css">

  <%= stylesheet_link_tag 'site', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'site', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

</head>
<body>
<div id="wrapper">
  <%= render 'layouts/site_header'%>

  <%= yield %>

  <%= render 'layouts/site_footer' %>
</div>

<script>
    <% if @page_properties[:half_banner] %>
    $(window).resize(function(){ SetHalfPageBanner(); });
    $(window).load(function(){ SetHalfPageBanner(); });
    <% else %>
    $(window).resize(function(){ SetFullPageBanner(); });
    $(window).load(function(){ SetFullPageBanner(); });
    <% end %>
</script>

</body>
</html>

app/views/layouts/error_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Katofresh</title>
  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">-->
  <!--<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >-->

  <!-- Google fonts -->
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans|Poiret+One|Josefin+Sans:400,600|Questrial|Catamaran:400,500' rel='stylesheet' type='text/css'>
  <!-- -->

  <link rel="stylesheet" href="/offline_assets/bootstrap.min.css">
  <link rel="stylesheet" href="/offline_assets/bootstrap.min.js">
  <link rel="stylesheet" href="/offline_assets/font-awesome.min.css">
  <link rel="stylesheet" href="/offline_assets/jquery-1.11.1.js">

  <link rel="script" href="/offline_assets/jquery-1.11.1.js">
  <link rel="stylesheet" href="/lightbox/css/lightbox.css">

  <%= stylesheet_link_tag 'site', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<div id="wrapper">
  <%= render 'layouts/site_header'%>

  <%= yield %>

</div>

<script>
  $(window).resize(function(){ SetHalfPageBanner(); });
  $(window).load(function(){ SetHalfPageBanner(); });
</script>

</body>
</html>